dict = {
    'AA': 'open', 'AKs': 'open', 'AQs': 'open', 'AJs': 'open', 'ATs': 'open',
    'A9s': 'open', 'A8s': 'open', 'A7s': 'open', 'A6s': 'open', 'A5s': 'open',
    'A4s': 'open', 'A3s': 'open', 'A2s': 'open', 'AKo': 'open', 'KK': 'open',
    'KQs': 'open', 'KJs': 'open', 'KTs': 'open', 'K9s': 'open', 'K8s': 'open',
    'K7s': 'open', 'K6s': 'open', 'K5s': 'open', 'K4s': 'open', 'K3s': 'open',
    'K2s': 'open', 'AQo': 'open', 'KQo': 'open', 'QQ': 'open', 'QJs': 'open',
    'QTs': 'open', 'Q9s': 'open', 'Q8s': 'open', 'Q7s': 'open', 'Q6s': 'open',
    'Q5s': 'open', 'Q4s': 'open', 'Q3s': 'open', 'Q2s': 'open', 'AJo': 'open',
    'KJo': 'open', 'QJo': 'open', 'JJ': 'open', 'JTs': 'open', 'J9s': 'open',
    'J8s': 'open', 'J7s': 'open', 'J6s': 'open', 'J5s': 'open', 'J4s': 'open',
    'J3s': 'open', 'J2s': 'open', 'ATo': 'open', 'KTo': 'open', 'QTo': 'open',
    'JTo': 'open', 'TT': 'open', 'T9s': 'open', 'T8s': 'open', 'T7s': 'open',
    'T6s': 'open', 'T5s': 'open', 'T4s': 'open', 'T3s': 'open', 'T2s': 'open',
    'A9o': 'open', 'K9o': 'open', 'Q9o': 'open', 'J9o': 'open', 'T9o': 'open',
    '99': 'open', '98s': 'open', '97s': 'open', '96s': 'open', '95s': 'open',
    '94s': 'open', '93s': 'open', '92s': 'open', 'A8o': 'open', 'K8o': 'open',
    'Q8o': 'open', 'J8o': 'open', 'T8o': 'open', '98o': 'open', '88': 'open',
    '87s': 'open', '86s': 'open', '85s': 'open', '84s': 'open', '83s': 'open',
    '82s': 'open', 'A7o': 'open', 'K7o': 'open', 'Q7o': 'open', 'J7o': 'open',
    'T7o': 'open', '97o': 'open', '87o': 'open', '77': 'open', '76s': 'open',
    '75s': 'open', '74s': 'open', '73s': 'open', '72s': 'open', 'A6o': 'open',
    'K6o': 'open', 'Q6o': 'open', 'J6o': 'open', 'T6o': 'open', '96o': 'open',
    '86o': 'open', '76o': 'open', '66': 'open', '65s': 'open', '64s': 'open',
    '63s': 'open', '62s': 'open', 'A5o': 'open', 'K5o': 'open', 'Q5o': 'fold',
    'J5o': 'fold', 'T5o': 'fold', '95o': 'fold', '85o': 'fold', '75o': 'open',
    '65o': 'open', '55': 'open', '54s': 'open', '53s': 'open', '52s': 'open',
    'A4o': 'open', 'K4o': 'fold', 'Q4o': 'fold', 'J4o': 'fold', 'T4o': 'fold',
    '94o': 'fold', '84o': 'fold', '74o': 'fold', '64o': 'fold', '54o': 'open',
    '44': 'open', '43s': 'open', '42s': 'open', 'A3o': 'open', 'K3o': 'fold',
    'Q3o': 'fold', 'J3o': 'fold', 'T3o': 'fold', '93o': 'fold', '83o': 'fold',
    '73o': 'fold', '63o': 'fold', '53o': 'fold', '43o': 'fold', '33': 'open',
    '32s': 'open', 'A2o': 'open', 'K2o': 'fold', 'Q2o': 'fold', 'J2o': 'fold',
    'T2o': 'fold', '92o': 'fold', '82o': 'fold', '72o': 'fold', '62o': 'fold',
    '52o': 'fold', '42o': 'fold', '32o': 'fold', '22': 'open'
}

def ret_dict():
  return dict